### ISSUE TITLE
Check that each gene name from the Annotation file is found in your gene counts matrix file and also in your gff3 file

### ISSUE THREAD

**Issue by hputnam** [hputnam/Becker_E5#14]
Your Annotation file should have 27,439 genes that were identified by blasting the protein fasta file, which clearly identifies the protein name and links it directly to the original genome paper. Therefore, you need to ensure that your gene counts matrix file gene ids match it for annotation of DEGs.  

Also the gff3 file needs to match gene id exactly to calculate the correct gene lengths and to join the files for GO analysis

**Comment by daniellembecker** [comment]
Checked that gene count matrix file and gffs file match exactly for gene_ids in DESeq2 code to start off all analyses here, see lines 185-198 for comparison: [DESeq2](https://github.com/hputnam/Becker_E5/blob/master/RAnalysis/Scripts/RNA-seq/Host/Host_Differential_Gene_Expression_Analysis.Rmd)

However, looking back into my [functional annotation assembly script](https://github.com/hputnam/Becker_E5/blob/master/Functional_Annotation/Scripts/pver_annot_compile.Rmd), even though the [output file ](https://github.com/hputnam/Becker_E5/blob/master/Functional_Annotation/Final_Annotations/pver_GOterms_interprot_swissprot_blast_trembl_20211203.csv) has 27,439 unique genes there were still unmatched gene_ids between it and the gff3, so tracking some of the unmatched genes through the script (ex: "Pver_g408", "Pver_g3070", "Pver_novel_701_5de57afd") which show that the functional annotation file that was blasted to the original protein fasta file has naming issues. Currently looking into where the divide is occurring and where the pattern is.

**Comment by hputnam** [comment]
@daniellembecker check the code here for how I dealt with it: https://github.com/hputnam/Poc_RAPID/blob/main/RAnalysis/scripts/Embryo_GeneExpression.Rmd

**Comment by daniellembecker** [comment]
@hputnam I think your repo is private the link isn't working and I don't see it on you repo list 

<img width="1071" alt="Screen Shot 2024-06-07 at 12 50 01 PM" src="https://github.com/hputnam/Becker_E5/assets/40968353/96d06870-7b98-4df6-909d-3e52ca70d4d1">

**Comment by hputnam** [comment]
try again

**Comment by daniellembecker** [comment]
all now match from edits on line 188-229: [code](https://github.com/hputnam/Becker_E5/blob/master/RAnalysis/Scripts/RNA-seq/Host/Host_Differential_Gene_Expression_Analysis.Rmd)
