### ISSUE TITLE
add any code for and output files of modification of the Pver genome gff file to the repository

### ISSUE THREAD

**Issue by hputnam** [hputnam/Becker_E5#3]

**Comment by hputnam** [comment]
Add directly to Step 7 here: https://github.com/hputnam/Becker_E5/blob/master/Bioinformatics/Workflows/P.verrucosa_RNASeq_Workflow.md

instead of referencing the issue link: https://github.com/Putnam-Lab/Lab_Management/issues/11

**Comment by daniellembecker** [comment]
Completed: https://github.com/hputnam/Becker_E5/blob/master/Bioinformatics/Workflows/P.verrucosa_RNASeq_Workflow.md

**Comment by hputnam** [comment]
What is the sanity check that what was done in the perl script is correct?
Do the gff compare results indicate there is still an issue with the modified gff file?
![Screenshot 2024-05-31 at 9 17 41 AM](https://github.com/hputnam/Becker_E5/assets/5198996/7623ed4f-e369-4732-b30c-5a589004c1ce)

**Comment by daniellembecker** [comment]
After we made the correction to the Pver_genome_assembly_v1.0.gff3 file, I tested the new Pver_genome_assembly_v1.0.modified.gff3 reference file on one test sample file and was able to work through the entire workflow with no issues to create a gene matrix. We were no longer receiving the: "Error: Traceback (most recent call last): File "prepDE.py", line 158, in t_id=RE_TRANSCRIPT_ID.search(v[8]).group(1) AttributeError: 'NoneType' object has no attribute 'group'" with the modified file and the

 "- INPUT     ["ID=cds.Pver_g25526.t1;Parent=Pver_g25526.t1", "5_prime_partial true", "3_prime_partial true"]
- OUTPUT    "ID=cds.Pver_g25526.t1;Parent=Pver_g25526.t1;5_prime_partial=true;3_prime_partial=true"" was consistent through all files.

**Comment by daniellembecker** [comment]
The gffcompare output shows that our transcriptome assembly matches the reference annotations across all metrics and there are no missed or novel features, and the sensitivity and precision are 100% at every level, suggesting that our initial assembly was accurate and the reference annotation was comprehensive and precise

**Comment by hputnam** [comment]
What is happening here in red?
![Screenshot 2024-05-31 at 9 17 41 AM](https://github.com/hputnam/Becker_E5/assets/5198996/744f410e-8016-4748-bb2d-8a2b3ac61674)

**Comment by daniellembecker** [comment]
hmm that is showing that out of the 27,439 query mRNAs in our assembly, 27,438 transcripts match the reference annotations except for there is one less matching transcript than the total number of query transcripts 

I went back to compare the original .gff3 and modified .gff3 so it is not missing the original transcript but I am looking into the unmatched transcript now

<img width="617" alt="Screen Shot 2024-05-31 at 10 43 48 AM" src="https://github.com/hputnam/Becker_E5/assets/40968353/a6c8f4a1-1bb7-4bdc-b449-0c07eacaa85f">

**Comment by daniellembecker** [comment]
Found the transcript:

<img width="1376" alt="Screen Shot 2024-05-31 at 11 08 04 AM" src="https://github.com/hputnam/Becker_E5/assets/40968353/c6bb3215-64c7-4d4e-ba9d-23566b934d9e">

The -k class code indicates that this transcript is fully contained/enclosed within a reference transcript from the provided reference annotation

**Comment by daniellembecker** [comment]
This transcript is still present and has values in my transcript and gene count matrices so I do not think it interrupted downstream analyses but I haven't heard of this before so looking into it further:

https://github.com/hputnam/Becker_E5/blob/master/RAnalysis/Data/RNA-seq/P.verrucosa/Host/Poc_gene_count_matrix.csv

https://github.com/hputnam/Becker_E5/blob/master/RAnalysis/Data/RNA-seq/P.verrucosa/Host/transcript_count_matrix.csv

**Comment by daniellembecker** [comment]
More information from paper and table 4: 


'=' Flag:
The '=' flag indicates that the query transcript has an identical intron chain as a reference transcript from the provided annotation. This means the query transcript has exactly the same exon-intron structure and coordinates as a reference transcript, except potentially different lengths for the terminal exons.

'k' Flag:
The 'k' flag means the query transcript is fully contained within (enclosed by) a reference transcript from the annotation. 'k' indicates it is a complete subset of a reference but with potential differences in terminal exon lengths or other minor variations from the reference model.

**Comment by daniellembecker** [comment]
added updates to workflows and added code for the modification of the Pver genome gff file to the repository on lines 86-130 [here](https://github.com/hputnam/Becker_E5/blob/master/RAnalysis/Scripts/RNA-seq/Host/Host_Differential_Gene_Expression_Analysis.Rmd)
