### ISSUE TITLE
Run one RNASeq sample in stringtie against a "fixed" gff3 and compare it to Polina's "modified" gff3 to see of counts are being assigned to the same gene

### ISSUE THREAD

**Issue by hputnam** [hputnam/Becker_E5#7]
https://github.com/hputnam/Becker_E5/blob/master/RAnalysis/Scripts/RNA-seq/fix_gff_format_AH.Rmd

The output of this script will created a gff3 file with "fixed" in the name

**Comment by daniellembecker** [comment]
@hputnam different counts are being assigned to each gene and transcript ID, see [step number 8 in my workflow](https://github.com/hputnam/Becker_E5/blob/master/Bioinformatics/Workflows/P.verrucosa_RNASeq_Workflow.md) where I ran stringtie on sample E9 against the "fixed" gff3 and the "modified" gff3.

I then looked at the comparison between the E9_R1_fixed_transcript_count_matrix.csv (pwd
/data/putnamlab/dbecks/Becker_E5/Becker_RNASeq/data/counts/gff3.count.compare)

![Screen Shot 2024-06-12 at 3 38 02 PM](https://github.com/hputnam/Becker_E5/assets/40968353/6e31ee89-d85f-4532-9f7c-0fefd821b57f)

and the E9_R1_modified_transcript_count_matrix.csv (pwd
/data/putnamlab/dbecks/Becker_E5/Becker_RNASeq/data/counts/gff3.count.compare)

![Screen Shot 2024-06-12 at 3 28 03 PM](https://github.com/hputnam/Becker_E5/assets/40968353/1eee639b-1f3c-4ce9-92ea-2aad85bc3ed4)

and they are very different in terms of number of counts per transcript, the modified have many more gene counts compared to the fixed gff3 so looking more into this

**Comment by daniellembecker** [comment]
I also ran this with the [updated workflow on the original published .gff3 ](https://github.com/hputnam/Becker_E5/blob/master/Bioinformatics/Workflows/P.verrucosa_RNASeq_Workflow.md)and thankfully that does match to my modified.gff3 counts, so maybe something in the [fixed.gff3 code](https://github.com/hputnam/Becker_E5/blob/master/RAnalysis/Scripts/RNA-seq/fix_gff_format_AH.Rmd) is throwing it off?

<img width="411" alt="Screen Shot 2024-06-12 at 4 13 15 PM" src="https://github.com/hputnam/Becker_E5/assets/40968353/0e95d9df-fb3c-4a82-9ba7-aec8df4c795e">

**Comment by hputnam** [comment]
@daniellembecker they are different approaches to solve the "problem" of non-matching names in the gff3 that gives stringtie problems

**Comment by hputnam** [comment]
We need to confirm which one has the most evidence of being correct in the way it is modifying the gff.

**Comment by hputnam** [comment]
Can you clarify what was changed in the "updated workflow on the original published .gff3 " statement above?

**Comment by hputnam** [comment]
my suggestion is taking IGV and looking at the bam files of several genes and seeing where they counts stack up and comparing that to the counts in the matrix

**Comment by daniellembecker** [comment]
> Can you clarify what was changed in the "updated workflow on the original published .gff3 " statement above?

I updated the workflow in section 8 to include the original .gff3 file along with the modified and fixed

**Comment by daniellembecker** [comment]
visual comparison for original and modified gff3 comparison to counts in the matrix seem logical and I do not see any inconsistencies between the original and modified gff3s for positions in various chromosome sequences

should we discuss further or can I move forward in updated analyses, etc.?

![Screen Shot 2024-06-18 at 9 06 33 AM](https://github.com/hputnam/Becker_E5/assets/40968353/929a7165-18b6-4a46-86c8-a38df7f71a0d)

**Comment by hputnam** [comment]
Yes, let's move forward with the modified version and the pearl script.

I also ran this script to check the modified and unmodified contents: https://github.com/hputnam/Poc_RAPID/blob/main/RAnalysis/scripts/compare_multiple_gffs.Rmd
