### ISSUE TITLE
Bioinformatics is using the "modified" gff and the GO enrichment is using the reefgenomics original gff

### ISSUE THREAD

**Issue by hputnam** [hputnam/Becker_E5#8]
There should only be one gff and all of the analyses should be using the same one.

**Comment by daniellembecker** [comment]
@hputnam the Pver_genome_assembly_v1.0.gene.gff3 is the "modified" gff but filtered for gene specific

**Comment by daniellembecker** [comment]
the GO enrichment is using the modified gff, filtered for gene only:

/data/putnamlab/dbecks/Becker_E5/Becker_RNASeq/data/refs/Pverr/Pver_genome_assembly_v1.0_modified.gff3

<img width="585" alt="Screen Shot 2024-05-30 at 3 51 42 PM" src="https://github.com/hputnam/Becker_E5/assets/40968353/c8638ba0-d328-4da2-8ac0-5d7021c120c2">


/data/putnamlab/dbecks/Becker_E5/Becker_RNASeq/data/refs/Pverr/Pver_genome_assembly_v1.0.gene.gff3

<img width="555" alt="Screen Shot 2024-05-30 at 3 49 10 PM" src="https://github.com/hputnam/Becker_E5/assets/40968353/187ceee4-51b8-4dc1-ad4a-2551c603b435">

we did this in the working group with Lenore

**Comment by daniellembecker** [comment]
sorry the naming is confusing but after modifying the .gff3, we did downstream changes only on that

**Comment by hputnam** [comment]
So here: 
https://github.com/hputnam/Becker_E5/blob/master/RAnalysis/Scripts/RNA-seq/Host/Host_GO_Enrichment_Analysis_Func_Annot.Rmd 

When you read in the GFF3, this is or looks like the one from the genome paper
GFF3 <- read.csv("RAnalysis/Genome/Pver_genome_assembly_v1.0.gene.gff3", header = FALSE, sep="", skip = 1)

Instead read in the modified one 
Pver_genome_assembly_v1.0_modified.gff3

Make sure there is only one file that says gff3 in your whole repo and always read in that one.

**Comment by daniellembecker** [comment]
Updated lines 54-74 to show the gene filter applied for the modified.gff3: https://github.com/hputnam/Becker_E5/blob/master/RAnalysis/Scripts/RNA-seq/Host/Host_GO_Enrichment_Analysis_Func_Annot.Rmd

deleted all other gff3 files and original reefgenomics annotation file from genome directory: https://github.com/hputnam/Becker_E5/tree/master/RAnalysis/Genome
